### ISSUE TITLE
Refactor: Separate integration tests from library functions

### ISSUE THREAD

**Issue by ojousima** [ruuvi/ruuvi.libraries.c#17]
e.g. make folder `integration_tests` and put all test files run on nRF52 there, and then update ruuvi.firmware.c SES and ARMGCC files to compile the libraries.

**Comment by opsationby** [comment]
https://github.com/ruuvi/ruuvi.firmware.c/pull/81 to fix  ruuvi.firmware.c SES and ARMGCC files to compile the libraries.

**Comment by ojousima** [comment]
Thanks
