### ISSUE TITLE
ruuvi_library_ringbuffer.c  ringbuffer_queue overflows buffer if data_length is too big

### ISSUE THREAD

**Issue by DG12** [ruuvi/ruuvi.libraries.c#2]
Should there be a check to make sure that the data_length does exceed the available space before the memcpy?

**Comment by ojousima** [comment]
The ringbuffer is meant to feed the softdevice during GATT connection event: 
This sets some really strict real-time requirements for the ringbuffer, as the connection uses connection event extension: the data has to be fed at the same rate as it is pushed out of the BLE connection, or the softdevice will terminate connection event data data rate drops dramatically.

On the other hand time to do a NULL pointer check and length check is probably negligible compared to memcpy, and there hasn't been an observed issue with the ringbuffer being too slow so maybe. I'll leave this issue open for now and check it once we have a GATT throughput demo to actually check the data rate achieved.

**Comment by ojousima** [comment]
I ended up adding the input checks in #9e3a80a while I was fixing #3. Thanks
